// Generated by https://quicktype.io

export interface PersonalData {
  name: string;
  brd: string;
  phone_number: string;
  email: string;
  location: string;
  github: string;
  linkedin: string;
  twitter: string;
  job_title: string;
  skills: Skill[];
  experience: Experience[];
  education: string;
  languages: Language[];
  interests: string[];
  projects: Project[];
  services: string[];
}

export interface Experience {
  title: string;
  company: string;
  location: string;
  from: string;
  to: string;
  description: string;
}

export interface Language {
  language: string;
  level: string;
}

export interface Project {
  name: string;
  description: string;
  images: string[];
  demo?: string;
}

export interface Skill {
  name: string;
  icon: string;
  description: string;
}

// Generated by https://quicktype.io

export interface Services {
  title: string;
  description: string;
  icon: string;
}
