// Generated by https://quicktype.io

export interface UserData {
  name: string;
  brd: string;
  phone_number: string;
  email: string;
  location: string;
  github: string;
  linkedin: string;
  twitter: string;
  job_title: string;
  education: string;
  interests: string[];
  services: string[];
}

export interface PersonalData extends UserData {
  skills: Skill[];
  experience: Experience[];
  projects: Project[];
  languages: Language[];
}

export interface ExperienceData {
  title: string;
  company: string;
  location: string;
  from: string;
  to: string;
  description: string;
}

export interface LanguageData {
  language: string;
  level: string;
}

export interface ProjectData {
  name: string;
  description: string;
  images: string[];
  demo?: string;
}

export interface SkillData {
  name: string;
  icon: string;
  description: string;
}

// Generated by https://quicktype.io

export interface ServicesData {
  title: string;
  description: string;
  icon: string;
}
